apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJuYW1sbi5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWkc5amEyVnlZM0psWkRwVFlYVmlaVzlBTVRFeCIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson